db:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=githook"
        - "MYSQL_USER=githook"
        - "MYSQL_PASSWORD=githook"
        - "MYSQL_DATABASE=githook"
engine:
    build: ./docker/engine/
    volumes:
        - "/Users/pdesgarets/dev/gitsync.php:/home/docker:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
        - "db:db"
    working_dir: "/home/docker"

front:
    image: nginx
    ports:
        - "8321:80"
    links:
        - "engine:engine"
    volumes:
        - ".:/home/docker:ro"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
