<?php

namespace AppBundle\Repository;

/**
 * RepoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepoRepository extends \Doctrine\ORM\EntityRepository
{
}
