AppBundle\Entity\Repo:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RepoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        fromUrl:
            type: string
            length: 255
        toUrl:
            type: string
            length: 255
    lifecycleCallbacks: {  }
